import type { NextPage } from "next";
import Head from "next/head";
import styles from '../styles/Home.module.css';
import  Header  from "../components/Header";
import Info from "../components/Info";
import NetworkSwitcher from "../components/Switcher";

const Home:NextPage=()=>{
    return (
        <>
            <Head>
                <title>My RainbowKit App</title>
                <meta content="Generated by @ranbow-me/create-rainbowkit"
                 name="description">
                </meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Header />
            
            <main className={styles.main}>
                <Info />
                <NetworkSwitcher/>
            </main>
            
            <footer className={styles.footer}>
                <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
                    Madewith by your frens at 🌈 “frens”:Unknown word.
                </a>
            </footer>
        </>
    )
}

export default Home;